### ISSUE TITLE
Image type not selected by docker (for linux/arm/v7)

### ISSUE THREAD

**Issue by flixhsw** [tomsquest/docker-radicale#110]
The description on  https://hub.docker.com/r/tomsquest/docker-radicale says: "The correct image type for your architecture will be automatically selected by Docker."
This does not seem to be the case. On a Raspberry Pi 4 (linux/arm/v7) with this configuration for docker-compose:

```
  radicale:
    container_name: radicale
    image: tomsquest/docker-radicale
    volumes:
      - ./radicale:/data
    ports:
      - 5232:5232
    restart: unless-stopped
```

I get:
```
$ docker-compose up -d
Pulling radicale (tomsquest/docker-radicale:)...
latest: Pulling from tomsquest/docker-radicale
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```
However, when I specify the image as `image: tomsquest/docker-radicale:arm.3.0.6.0` it is working.

Another question:
My first (wrong) thought was, that no arm images are available and I was about to start work on a PR for building arm images. While looking through the code, I found that ci/build-push.sh only contains amd64 and arm64 archs and creates the manifest manually.

How are the arm images build, when only amd64 and arm64 are listed as architectures?
Why is docker buildx not used for building the multi-arch image?
