### ISSUE TITLE
data folder on host has wrong owner

### ISSUE THREAD

**Issue by blue1stone** [tomsquest/docker-radicale#125]
Hey!
First of all, thanks for making this, it has really come in handy for me!

However, I ran into a slight problem:
I would like to protect my `data` folder on my host using `chmod o=`, but when I do this, I get an error from the radicale container that it can no longer read the folder.

Those are the permissions given to the folder when I change nothing:
`drwxrwxr-x 3 168534 168534 4096 Feb  5 18:13 data`

I have also created a radicale user with uid and gid `2999`. However, the folder does not seem to be owned by this user in the first place?

Do you have an idea what I am doing/understanding wrong?

For reference, my `docker-compose.yml` is the following:
```
version: '3.7'

services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    restart: unless-stopped
    ports:
      - 127.0.0.1:5232:5232
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    volumes:
      - /path/to/radicale/data:/data
      - /path/to/radicale/config:/config:ro
      - /path/to/radicale/users:/users:ro
```
