### ISSUE TITLE
docker-compose fails to start container

### ISSUE THREAD

**Issue by inglar** [tomsquest/docker-radicale#137]
docker-compose.yaml
```
# Can be enhanced with additional compose file 
# See also https://docs.docker.com/compose/production/#modify-your-compose-file-for-production

version: '3.7'

services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - 127.0.0.1:5232:5232
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./data:/data
```

```
docker-compose up -d
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.radicale.deploy.resources.limits value Additional properties are not allowed ('pids' was unexpected)
```
If i comment `pids: 50` line it successfully starts.
Can't figure out what is the problem with default docker compose file.
