### ISSUE TITLE
A problem on using config file in container

### ISSUE THREAD

**Issue by mcanyucel** [tomsquest/docker-radicale#148]
Even though I map the config file as a volume, radicale does not use this config file; it uses defaults. I know this because even if I change the port to 7777, it runs at 5232 and it does not use the userfile (not prints any logs).

I have the following compose file:

```yaml
services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    init: true
    read_only: true
    networks:
      - caddy_network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config/config:/etc/radicale/config:ro
      - ./config/users:/etc/radicale/users:ro

networks:
  caddy_network:
    external: true
```

I have the config file under config/config (it is mapped to the /etc/radicale/config as readonly)

```
[server]

hosts = localhost:7777
...
[auth]

# Authentication method
# Value: none | htpasswd | remote_user | http_x_remote_user
type = htpasswd

# Htpasswd filename
htpasswd_filename = /etc/radicale/users

# Htpasswd encryption method
# Value: plain | bcrypt | md5
# bcrypt requires the installation of radicale[bcrypt].
htpasswd_encryption = md5

# Incorrect authentication delay (seconds)
# delay = 1

# Message displayed in the client when a password is needed
# realm = Radicale - Password Required


[rights]

# Rights backend
# Value: none | authenticated | owner_only | owner_write | from_file
# type = owner_only

# File for rights management from_file
#file = /etc/radicale/rights


[storage]

# Storage backend
# Value: multifilesystem | multifilesystem_nolock
#type = multifilesystem

# Folder for storing local collections, created if not present
#filesystem_folder = /var/lib/radicale/collections
# filesystem_folder = /data/collections

# Delete sync token that are older (seconds)
#max_sync_token_age = 2592000

# Command that is run after changes to storage
# Example: ([ -d .git ] || git init) && git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s)
#hook =

[web]

# Web interface backend
# Value: none | internal
type = none


[logging]

# Threshold for the logger
# Value: debug | info | warning | error | critical
level = info

# Don't include passwords in logs
#mask_passwords = True


[headers]

# Additional HTTP headers
#Access-Control-Allow-Origin = *
```

I check the presence of the file within the container using `docker exec -it radicale /bin/sh` and it is there:

```bash
/ # ls -la /etc/radicale/
total 16
drwxr-xr-x    2 root     root          4096 May 22 13:54 .
drwxr-xr-x    1 root     root          4096 May 22 13:54 ..
-rw-r--r--    1 root     root          2451 May 22 13:56 config
-rw-r--r--    1 root     root            48 May 22 13:23 users
```

But it does not use these files. Should I make them owned by user 2999? Or any other ideas?

PS: In the host computer, every user has read permission for the files:

```bash
styx@valinor:~/containers/radicale$ ls -la config/
total 16
drwxr-xr-x 2 styx styx 4096 May 22 16:56 .
drwxr-xr-x 4 styx styx 4096 May 22 16:54 ..
-rw-r--r-- 1 root root 2451 May 22 16:56 config
-rw-r--r-- 1 root root   48 May 22 16:23 users
```
