### ISSUE TITLE
Questions about using in compose

### ISSUE THREAD

**Issue by yishangfei** [tomsquest/docker-radicale#166]
```
    radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    network_mode: bridge
    ports:
      - 15232:5232
    init: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - /volume3/Docker/radicale:/data
```

I would like to know how to block web access like [vCards](https://github.com/metowolf/vCards)
Subscription address: [vcards.metowolf.com](https://vcards.metowolf.com)
