### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by AlexKalopsia** [tomsquest/docker-radicale#82]
Hi, I am trying to run Radicale using docker-compose but as soon as I get the container running, the log shows this:

```
ERROR: An exception occurred during server startup: Failed to start server '192.168.1.200:5232': [Errno 99] Address not available
```

I can't reach  http://localhost:5232/. any idea what could be causing this? 

my docker-compose looks like this

```
radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    ports:
      - 127.0.0.1:5232:5232
    volumes:
      - /volume1/docker/radicale/data:/data
      - /volume1/docker/radicale/config:/config:ro
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f myip:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
```

**Comment by tomsquest** [comment]
Hi @AlexKalopsia ,
I think that the healthcheck should stick with 127.0.0.1, not the IP address of your host. This address should be accessible by the container and, with Docker, the container has no knowledge of the network of your host.

**Comment by AlexKalopsia** [comment]
@tomsquest that didn't fix the issue :( I still get the same error, saying that myip:5232 is not available

I've tried mapping radicale to a different port in docker-compose, but no success. My docker-compose now looks like this:

```
  radicale:
    image: tomsquest/docker-radicale:latest
    container_name: radicale
    ports:
      - 5232:5232
    volumes:
      - /volume1/docker/radicale/data:/data
      - /volume1/docker/radicale/config:/config:ro
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
```

I've also tried `otherport:5232`
