### ISSUE TITLE
no config file created

### ISSUE THREAD

**Issue by dkebler** [tomsquest/docker-radicale#99]
just doing a quick eval of radicale but looks like your Dockerfile is not creating the intial config file 

`radicale    | [2021-10-12 18:25:55 +0000] [7] [CRITICAL] Invalid configuration: Failed to load config file '/config/config': No such file: '/config/config'
`

so after running once I created config file from your example in my host volume and then restarted and that seemed to work.

using compose file

```yaml
version: '3.7'

services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - 5232:5232
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    healthcheck:
      test: curl -f http://localhost:5232 || exit 1
      interval: 30s
      retries: 3
#   restart: unless-stopped
    volumes:
      - ./data:/data
      - ./config:/config:ro
```
